void tree2r() {

	// read the Tree generated by tree2w and fill one histogram
	// we are only interested by the destep branch

	// note that we use "new" to create the TFile and TTree objects because we
	// want to keep these objects alive when we leave this function
	TFile *f = new TFile("Run1Data.root");
	TTree *tr = (TTree*)f->Get("Data");
	static Float_t destep;
	TBranch *x_destep = tr->GetBranch("Pre-Step X");
	TBranch *y_destep = tr->GetBranch("Pre-Step Y");
	TBranch *z_destep = tr->GetBranch("Pre-Step Z");
	x_destep->SetAddress(&xdestep);
	y_destep->SetAddress(&ydestep);
	z_destep->SetAddress(&zdestep);

	//create one histogram
	TH1F *hdestep = new TH1F("hdestep", "destep in Mev", 100, 1e-5, 3e-5);
	//read only the destep branch for all entries
	Int_t nentries = (Int_t)t2->GetEntries();
	for (Int_t i = 0; i < nentries; i++) {
		b_destep->GetEntry(i);
		// fill the histogram with the destep entry
		hdestep->Fill(destep);
	}

	// we do not close the file; we want to keep the generated histograms;
	// we fill a 3-d scatter plot with the particle step coordinates
	TCanvas *c1 = new TCanvas("c1", "c1", 600, 800);
	c1->SetFillColor(42);
	c1->Divide(1, 2);

	c1->cd(1);
	hdestep->SetFillColor(45);
	hdestep->Fit("gaus");

	c1->cd(2);
	gPad->SetFillColor(37);                       // continued...
	t2->SetMarkerColor(kRed);
	t2->Draw("vect[0]:vect[1]:vect[2]");
	if (gROOT->IsBatch()) return;

	// invoke the x3d viewer
	gPad->GetViewer3D("x3d");
}