# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
# Change the default number of workers (in multi-threading mode) 
#/run/numberOfWorkers 4
#
# Initialize kernel
/run/initialize
#
/control/verbose 2
/run/verbose 2
/event/verbose 0
/tracking/verbose 1
# 
# electron 1 MeV to the direction (1.,0.,0.)
# 3 events
/gun/particle e-
/gun/energy 1 MeV
# 
/tracking/verbose 0
/run/printProgress 5
/run/beamOn 300000


